repository: iswc-reproducibility/iswc-reproducibility.github.io
title: SIGMOD Reproducibility Effort
description: SIGMOD Reproducibility Effort (ISWC)
plugins:
  - jekyll-remote-theme
remote_theme: "mmistakes/jekyll-theme-basically-basic"
