repository: iswc-reproducibility/iswc-reproducibility.github.io
title: ISWC-Reproducibility Initiative
description: ISWC-Reproducibility Initiative (ISWC)
plugins:
  - jekyll-remote-theme
#remote_theme: "mmistakes/jekyll-theme-basically-basic"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
logo: "/assets/images/logooo.png"
